### ISSUE TITLE
There is a problem with the directory /app/public

### ISSUE THREAD

**Issue by ivroche** [juliangut/docker-phpdev#18]
$ docker-compose up
Creating network "dockerlaravel_default" with the default driver
Creating dockerlaravel_app_1 ... done
Attaching to dockerlaravel_app_1
app_1  | Directory /app/public does not exist.
dockerlaravel_app_1 exited with code 1
Directory /app/public does not exist.

**Comment by juliangut** [comment]
Hi @utsocial 

Can you please give some more information to identify the problem? any of the images create a /app/public directory, only /app directory, so I assume you're correctly mounting your local Laravel project on /app

What image version are you using? are you launching PHP's internal web server or FPM? can you copy/paste your Dockerfile?

**Comment by juliangut** [comment]
Closing as no feedback provided
